services:
  - type: web
    name: infografika-ai-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

      - key: OPENAI_API_KEY
        sync: false

      - key: BOT_TOKEN
        sync: false
